// Static, prebuilt copy of the published roadmap.
//
// On Vercel the SQLite file could not be opened (SQLITE_CANTOPEN): a .db is
// opened by runtime path, so Next's file tracer does not reliably ship it into
// the lambda. A JSON `import` is a real module edge, so webpack always bundles
// it — no file tracing, no better-sqlite3 at runtime.
//
// Regenerated by `npm run db:pack` from the published snapshot in roadmap.db.
import published from "../data/published.json";
import type { ProductWithItems } from "./db";

export interface StaticSnapshot {
  products: ProductWithItems[];
  published_at: string | null;
  changelog: any[];
}

export const SNAPSHOT = published as unknown as StaticSnapshot;
